# Generated by Django 4.2.5 on 2023-10-02 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_alter_customer_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='basket',
        ),
    ]
