# Generated by Django 4.2.5 on 2023-10-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_customer_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='registration_date',
            field=models.DateField(auto_created=True),
        ),
    ]
